# Generated by Django 5.2 on 2025-04-08 06:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pet_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('last_stat_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('hunger', models.IntegerField(default=70)),
                ('happiness', models.IntegerField(default=70)),
                ('energy', models.IntegerField(default=70)),
                ('health', models.IntegerField(default=100)),
                ('stage', models.CharField(choices=[('baby', 'Baby'), ('teen', 'Teen'), ('adult', 'Adult')], default='baby', max_length=20)),
                ('experience', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('alive', 'Alive'), ('sleeping', 'Sleeping'), ('sick', 'Sick'), ('deceased', 'Deceased')], default='alive', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='pet_api.pet')),
            ],
        ),
    ]
