# Generated by Django 5.2 on 2025-04-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='energy',
            new_name='hygiene',
        ),
        migrations.AddField(
            model_name='pet',
            name='sleep',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='pet',
            name='sleep_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
