# Generated by Django 5.2 on 2025-04-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_api', '0002_rename_energy_pet_hygiene_pet_sleep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='happiness',
            field=models.IntegerField(default=700),
        ),
        migrations.AlterField(
            model_name='pet',
            name='health',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='pet',
            name='hunger',
            field=models.IntegerField(default=700),
        ),
        migrations.AlterField(
            model_name='pet',
            name='hygiene',
            field=models.IntegerField(default=700),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sleep',
            field=models.IntegerField(default=700),
        ),
    ]
